name: yeowoobi_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_quill: ^11.2.0
  flutter_quill_extensions: ^11.0.0
  path_provider: ^2.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/image/logo_white.png
     - assets/image/logo_orange.png
     - assets/image/kakao_login_large_wide.png
     - assets/image/fox.png
     - assets/icons/
     - assets/background/
     - assets/dummy.json
     - assets/new.json
     - assets/template.json
     - assets/image/q1.png
     - assets/image/q2.png
     - assets/questions.json
     - lib/board/free_board_dummy.json
     - lib/sns/sns_dummy.json